### ISSUE TITLE
Chat Issue

### ISSUE THREAD

**Issue by Arctiblaine** [imjack/Factions-For-Nukkit#1]
After creating a faction name, description, and tag, my players will normally get a message upon sending a message.

"c**Taigains hat.type.text

Players who haven't joined a Faction, created one etc get this message instead

<{%0}> [%1}

I have tried going into the config.json but I could not find anything for this.

**Reproduce**
1) Create a faction
2) Create a description
3) Create a player tag

OR

1) Don't do the following above, and get this message instead:

<{%0}> [%1}

**Devices**
I am using Windows 7
My device was a Samsung Galaxy Tab 2 lite (2013)

**Comment by imjack** [comment]
Many people have found this bug, although I can't seem to fix it without messing up the chat for other plugins. Unless someone would like to find a fix. A method I found was using MadPerms with this formart format: '[FACTION] %p%s%n&f: %m' and this faction config https://gist.github.com/imjack/b72d0f2ca7f5512755149afe774215a9

**Comment by Arctiblaine** [comment]
I am going to try this.. but although I do not use a chat plugin, the only
permissions plugin I use is LeetPerms. Is this plugin affecting
Factions-for-Nukkit?

**Comment by imjack** [comment]
No its not leetperms its factions. This is just one of the fixes I've found. I'm currently busy with other projects currently

**Comment by Arctiblaine** [comment]
Ah, I see.
I've just tried testing it and it's blank. Well, it may be the colors of
the chat. I'm not exactly sure. Did I enter it wrong? It does show in the
console as

(flipped ō)**Taigains7[P] tiNsLeY799: It's blank on screen.

**Comment by Arctiblaine** [comment]
Scratch that.. I kept editing MadPerms' configure file while the server was
running.

Thank you so much for your help!
