### ISSUE TITLE
OMGGGG I LOVE YOU SO MUCH MUCH MUCH

### ISSUE THREAD

**Issue by ghost** [imjack/Factions-For-Nukkit#4]
I LOVE YOU SO MUCH MUCH MUCH BECAUSE YOU CREATED THIS PLUGIN !!!!!!!!!!!!!!!!!

**Comment by imjack** [comment]
:+1:

**Comment by ghost** [comment]
@imjack ,you can create more plugins from Spigot/Bukkit? :)

E.g. : https://mods.curse.com/bukkit-plugins/minecraft/clearlagg
https://mods.curse.com/bukkit-plugins/minecraft/pvp-1vs1
https://mods.curse.com/bukkit-plugins/minecraft/skyblock
https://mods.curse.com/bukkit-plugins/minecraft/b173gen ??????

Thanks :)

**Comment by imjack** [comment]
Nah, I ported factions since I intended to use it. The plugins above I don't.

**Comment by ghost** [comment]
Why @imjack  ?

**Comment by imjack** [comment]
Well the plugins you posted I'll never use them so why would I want to waste my time porting them.

**Comment by ghost** [comment]
You can port one skyblock plugin? @imjack  :)

**Comment by ghost** [comment]
And generator plugin is for better world :)

**Comment by imjack** [comment]
because i'm creating a private skyblock and for generation just pre-gen a pc map. Nukkits generation isn't too bad.

**Comment by ghost** [comment]
@imjack And skyblock plugin work?

**Comment by imjack** [comment]
What?

**Comment by Shock95** [comment]
I think he's asking if your private SkyBlock plugin functions.

**Comment by ghost** [comment]
@imjack I can test your plugin skyblock? :)

**Comment by imjack** [comment]
It will be private sorry. There is a public skyblock floating around on github.

**Comment by ghost** [comment]
@imjack Yes but is very very buggy

**Comment by imjack** [comment]
Well get him to fix the bugs.

**Comment by ghost** [comment]
Ok,you can add and all commands from pc ? @imjack :)

**Comment by imjack** [comment]
Why would I do that? I'm creating my own private plugin

**Comment by ghost** [comment]
Ah,ok @imjack
