### ISSUE TITLE
Chat Bug

### ISSUE THREAD

**Issue by LinuxLogo** [imjack/Factions-For-Nukkit#9]
When you type in chat "c**Test hat.type.text" is what you see

**Comment by imjack** [comment]
read #1 Since I'm not running factions currently I haven't been interested in updating it.

**Comment by ghost** [comment]
@imjack I'm fixed this problem without your config..

**Comment by ghost** [comment]
Need use format. If you not use format ,get bug.

**Comment by imjack** [comment]
Assuming you want an the tag then you will.

**Comment by FilleDev** [comment]
Is there a solution?

**EDIT:** 
Nvm, fixed it by myself
https://i.gyazo.com/d2eb603b801a96bf731c44de992fe251.png

**Comment by CoolGuyMC** [comment]
@File14 How did you fix it? Mind telling me?
